apiVersion: v1
kind: Config
current-context: kubernetes-admin
contexts:
- context:
    cluster: ${cluster_name}
    user: ${user_name}
  name: kubernetes-admin
clusters:
- cluster:
    server: ${endpoint}
    certificate-authority-data: ${cluster_ca}
  name: ${cluster_name}
users:
- name: ${user_name}
  user:
    token: ${user_token}
